### PR TITLE
added ability to cache class methods

### PR DESCRIPTION
**Pull request by ScotterC**
caching class methods which expire upon any instance being updated.

### CODE REVIEW

**Comment by flyerhzm** [comment]
@ScotterC I'm afraid I don't think it's a good idea, it's difficult to determine when to expire class methods, e.g. if you get [a, b, c] from class method cache posts_by_first_user, you have to expire the cache when post d added to first_user's posts or post c removed from first_user's posts.

**Comment by ScotterC** [comment]
I was going more for a direct equivalent to the #with_method.  Using the collection was a bad example.  What about more like a Country.default method etc.  

Technically you can make the same falter with the #with_method method

**Comment by flyerhzm** [comment]
Yes, you are right. So my suggestion is to change the example of with_class_method in README and it would be better to say "not recommend using with_method, with_class_method for collection", what do you think?

**Comment by ScotterC** [comment]
See: https://github.com/flyerhzm/simple_cacheable/pull/18

**Pull request merged**
