### PR TITLE
Clean up. 

### PR DESCRIPTION
**Pull request by ScotterC**
cleaning out EOFs and replace with define_method and define_singleton_methods.

I broke up the file into three.  CacheTypes, ClassMethods and InstanceMethods for better clarity.  It makes it a lot easier to compartmentalize and work on the code.  Thoughts on the naming convention are welcome. 

I thought about breaking out each cache method into it's own file, because that `with_association` definition is a behemoth but that felt counter productive.

### CODE REVIEW

**Comment by flyerhzm** [comment]
It's a good start, but I'd like to break up files by functionalities, like `key_cache.rb`, `attribute_cache`, `method_cache`, etc.

**Comment by ScotterC** [comment]
I was thinking that at first too.  I hesitated before because I wasn't sure if it was overkill or not.  I'll get on it tomorrow.

**Comment by flyerhzm** [comment]
The good point by functionalities is code in each file are independent, you define and use the code in the same file.

But by class methods and instance methods, you define the cache keys in class methods file, but use them in instance methods file, it makes code a bit difficult to read.

**Comment by ScotterC** [comment]
Alright.  This should be easier to read.
- All cache types are in a folder.
- All expiration related logic is in one file.
- All key creation logic is in one place, for both class and instance methods
- The main model_cache method resides in the main cacheable file

Reorganized specs to match which slimmed down on what data was needed.

What do you think

**Comment by flyerhzm** [comment]
looks pretty good, thanks

**Comment by flyerhzm** [comment]
btw, you can release a new version for such big change.

**Comment by ScotterC** [comment]
Great.  Will do.

**Pull request merged**
